### ISSUE TITLE
Unable to Respawn after dying [1.21] [Bug] 

### ISSUE THREAD

**Issue by rAstrae** [quiqueck/WorldWeaver#3]
### What happened?

What happened? I died and could not respawn.
What I expected to happen? I would respawn.
/jk
But yeah, for some reason...

### BCLib

21.0.0

### Fabric API

0.100.3+1.21

### Fabric Loader

0.15.11

### Minecraft

1.20.1

### Relevant log output

```shell
Nothing said in the log which is troublesome I guess.
But when I click respawn it appears to be "pressed", but no action is taken afterwards (No respawn) and just the button "regenerates" back to normal, going back to main menu is working as intended.
```

### Other Mods

```World Weaver``` - ```BClib``` - ```Better Nether``` <- Deleting them fixed the issue - obviously. (I was forced to delete ```bdclib``` and ```better nether``` anyway...)

**Comment by JaTheDemon** [comment]
It is a Bugged affiliated with the better nether mod its better just to not have the mod installed until fixed

**Comment by quiqueck** [comment]
Should be fixed in the latest release.
