### ISSUE TITLE
Axe Harvest Bugged 1.21[Bug] 

### ISSUE THREAD

**Issue by JaTheDemon** [quiqueck/WorldWeaver#4]
### What happened?

When having BCLib and World Weaver installed Block Harvest speed is all set to the speed of harvesting with fist for all axes, I haven't tested with other blocks that involve other tools but for sure i know that all axes are completely bugged.

### BCLib

21.0.2

### Fabric API

0.100.3

### Fabric Loader

1.21

### Minecraft

1.20.1

**Comment by FAKHORII** [comment]
this one gave me a real headache, I have a lot of mods and had to test them 1 by 1, deleting them and starting the game and test, it took me a lot of time, none of the axes work, even moded ones, I came here to report this issue and found this already,
 idk why a mod like this interferes with a certain type of tools

**Comment by quiqueck** [comment]
Did you try this with the latest version? There was an issue where an item from one of the mienable tags was missing (there should be a line in the logs). But it was fixed with the last release.
