### ISSUE TITLE
[Bug] Unable to climb ladders 1.21

### ISSUE THREAD

**Issue by monenic** [quiqueck/WorldWeaver#7]
### What happened?

Unable to climb ladders when having both BCLib and World Weaver installed. Im using BCLib 21.0.3 and World Weaver 21.0.4

### BCLib

21.0.4

### Fabric API

0.100.4+1.21

### Fabric Loader

0.15.11

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
This should be fixed in the latest release.
