### ISSUE TITLE
[Bug] Incompatibile with Lithostitched

### ISSUE THREAD

**Issue by Apollounknowndev** [quiqueck/WorldWeaver#8]
### What happened?

*Same crash as #5 but with minimal mod setup and more info.*

When a world is created/loaded with both WorldWeaver and Lithostitched, the game crashes due to one of WorldWeaver's registries being missing. The [attached log](https://mclo.gs/Gw98n84) shows `biome_modifications` being missing, but `biome_data` and `surface_rules` have both been culprits as well in my testing.

Steps to reproduce:
- Install WorldWeaver 21.0.6, Fabric API 0.100.6, and Lithostitched 1.2.2 onto a 1.21 game instance.
- Create a new world.
- Crash.

I've tested several possible issues on Lithostitched's side such as it's worldgen modifier and surface rule system but could not come to a clear consensus, leading me to believe it's an issue on WorldWeaver's end.

**Comment by quiqueck** [comment]
First of all, thanks for digging into this. It is very appreciated. And I think i found the issue. It is a very basic race condition. When lithostitched is initialized, it will trigger the initialization of `RegistryDataLoader.WORLDGEN_REGISTRIES`. If wover was not yet loaded at that ttime our wover sub-modules did not yet have  a chance to prepare our own worldgen registries.

I think I know how to fix that issue...

**Comment by quiqueck** [comment]
Todays release should have this fixed (I hope)

**Comment by chorbintime** [comment]
fixed!
