### ISSUE TITLE
[Bug] Duplicate keys in VanillaRegistries bootstrap

### ISSUE THREAD

**Issue by Su5eD** [quiqueck/WorldWeaver#9]
### What happened?

Attempting to use `VanillaRegistries.createLookup()` results in an exception when WorldWeaver is installed. While this method doesn't seem to be called by vanilla unless `SharedConstants.IS_RUNNING_IN_IDE` is enabled, other mods are dependent on it, such as the [Fabric API](https://github.com/FabricMC/fabric/blob/f9000df732297d583eb96c98ec0341da06c1d1c6/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BuiltInRegistryKeys.java#L30).

I tested this in WorldWeavers's own dev environment using revision 04e0d37476a7dbad15e6af0533cf09153969fb2d. The Minecraft version is 1.21 (pointing this out as the issue template only allows me to select 1.20.1).

Steps to reproduce:
1. Run `runTestmodClient` in the `wover-biome-api` subproject
2. Hook into the loading process by placing a breakpoint in `net.minecraft.client.main.Main#main`, anything early enough works
3. Method 1: Call `VanillaRegistries.createLookup()` directly using the IDE evaluator.
4. Method 2: Set `SharedConstants.IS_RUNNING_IN_IDE` to `true`. Wait for vanilla to try calling `VanillaRegistries.createLookup()` from `Commands.validate()`
6. Experience a crash

Presumably, any mod that uses the fabric biome api would trigger a crash this way, although I couldn't think of any to test this out with.

### BCLib

N/A

### Fabric API

0.100.3+1.21

### Fabric Loader

21.0.8

### Minecraft

1.20.1

### Relevant log output

```shell
https://mclo.gs/g58EdI9
```

**Comment by quiqueck** [comment]
Thanks for reporting, and for the detailed description!

**Comment by quiqueck** [comment]
Should be fixed with the latest version.
